# Generated by Django 4.0.4 on 2022-07-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order_id',
        ),
    ]
